(set-frame-font "OverpassM Nerd Font Mono 20")
(set-frame-size (selected-frame) 140 45)
(global-display-line-numbers-mode)
(setq inhibit-startup-screen t)
(column-number-mode 1)
(scroll-bar-mode 0)
(show-paren-mode 1)
(menu-bar-mode 0)
(tool-bar-mode 0)
(tab-bar-mode 1)
