;; Keymap
(keymap-global-set "s-c"       'kill-ring-save)
(keymap-global-set "s-v"       'yank)
(keymap-global-set "s-x"       'kill-region)
(keymap-global-set "s-a"       'mark-whole-buffer)
(keymap-global-set "s-z"       'undo)
(keymap-global-set "s-o"       'find-file)
(keymap-global-set "s-w"       'tab-bar-close-tab)
(keymap-global-set "s-t"       'tab-bar-new-tab)
(keymap-global-set "s-s"       'save-buffer)
(keymap-global-set "s-S"       'mac-save-file-as) 
(keymap-global-set "s-q"       'save-buffers-kill-emacs)
(keymap-global-set "s-l"       'goto-line)
(keymap-global-set "s-k"       'kill-buffer)
(keymap-global-set "s-<up>"    'beginning-of-buffer)
(keymap-global-set "s-<down>"  'end-of-buffer)
(keymap-global-set "s-<left>"  'beginning-of-line)
(keymap-global-set "s-<right>" 'end-of-line)
(keymap-global-set "M-<down>"  'forward-paragraph)
(keymap-global-set "M-<up>"    'backward-paragraph)

;; Modifiers
(setq mac-option-modifier 'meta)
(setq mac-command-modifier 'super)
