;; Keymap
(global-set-key (kbd "s-c")       'kill-ring-save)
(global-set-key (kbd "s-v")       'yank)
(global-set-key (kbd "s-x")       'kill-region)
(global-set-key (kbd "s-a")       'mark-whole-buffer)
(global-set-key (kbd "s-z")       'undo)
(global-set-key (kbd "s-o")       'find-file)
(global-set-key (kbd "s-w")       'tab-bar-close-tab)
(global-set-key (kbd "s-t")       'tab-bar-new-tab)
(global-set-key (kbd "s-s")       'save-buffer)
(global-set-key (kbd "s-S")       'mac-save-file-as) 
(global-set-key (kbd "s-q")       'save-buffers-kill-emacs)
(global-set-key (kbd "s-l")       'goto-line)
(global-set-key (kbd "s-k")       'kill-buffer)
(global-set-key (kbd "s-<up>")    'beginning-of-buffer)
(global-set-key (kbd "s-<down>")  'end-of-buffer)
(global-set-key (kbd "s-<left>")  'beginning-of-line)
(global-set-key (kbd "s-<right>") 'end-of-line)
(global-set-key (kbd "M-<down>")  'forward-paragraph)
(global-set-key (kbd "M-<up>")    'backward-paragraph)

;; Modifiers
(setq mac-option-modifier 'meta)
(setq mac-command-modifier 'super)
